name: Terraform AI Reviewer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai python-dotenv

    - name: set up terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init
    
    - name: Generate Terraform Plan
      working-directory: ./terraform
      run: terraform plan -out=tfplan
    
    - name: Convert Terraform Plan to JSON
      working-directory: ./terraform
      run: terraform show -json tfplan > tfplan.json   

    - name: Run AI Reviewer
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python app/main.py